// SPDX-License-Identifier: MPL-2.0
//
// Interactive demo of the Mecojoni Unity integration.
//
// It spawns itself into whatever scene enters play mode (no scene asset or
// prefab wiring needed): open this project in Unity, press Play, and the
// results appear both on screen (IMGUI, so no font or package dependencies)
// and in the Console. Click the buttons (or press SPACE) for fresh lines;
// edit the name field to change the `playerName` input.

using System.Collections.Generic;
using Mecojoni;
using UnityEngine;

public sealed class MecojoniDemo : MonoBehaviour
{
    private readonly List<string> lines = new List<string>();
    private MecoGrammar hello;
    private MecoGrammar npc;
    private string playerName = "Ripley";
    private ulong nextSeed = 1000;
    private Vector2 scroll;

    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
    private static void Bootstrap()
    {
        if (FindObjectOfType<MecojoniDemo>() == null)
        {
            var host = new GameObject("MecojoniDemo");
            host.AddComponent<MecojoniDemo>();
            DontDestroyOnLoad(host);
        }
    }

    private void Log(string line)
    {
        Debug.Log(line);
        lines.Add(line);
    }

    private void Start()
    {
        try
        {
            Log(string.Format("Mecojoni versions: ffi_abi={0} core_api={1} bytecode={2}",
                MecoVersions.FfiAbi, MecoVersions.CoreApi, MecoVersions.Bytecode));
            hello = MecojoniDemoRunner.LoadHello(Log);
            npc = MecojoniDemoRunner.LoadNpc(Log);
            for (ulong seed = 0; seed <= 4; seed += 1)
            {
                MecojoniDemoRunner.Generate(Log, "hello", hello, seed, null);
            }
            var data = MecojoniDemoRunner.NpcData(playerName);
            for (ulong seed = 0; seed <= 2; seed += 1)
            {
                MecojoniDemoRunner.Generate(Log, "npc", npc, seed, data);
            }
            Log("Press the buttons (or SPACE) for more.");
        }
        catch (MecoException error)
        {
            Log("ERROR " + error.Message);
        }
        catch (System.DllNotFoundException error)
        {
            Log("Native library missing: run engines/unity/build.sh first, then " +
                "reopen the project. (" + error.Message + ")");
        }
    }

    private void OnDestroy()
    {
        hello?.Dispose();
        npc?.Dispose();
    }

    private void Update()
    {
        // Ignore the hotkey while the IMGUI text field has keyboard focus,
        // otherwise typing a space into playerName would also generate.
        if (Input.GetKeyDown(KeyCode.Space) && GUIUtility.keyboardControl == 0)
        {
            GenerateBoth();
        }
    }

    private void GenerateHello()
    {
        if (hello != null)
        {
            MecojoniDemoRunner.Generate(Log, "hello", hello, nextSeed++, null);
        }
    }

    private void GenerateNpc()
    {
        if (npc != null)
        {
            MecojoniDemoRunner.Generate(Log, "npc", npc, nextSeed++,
                MecojoniDemoRunner.NpcData(playerName));
        }
    }

    private void GenerateBoth()
    {
        GenerateHello();
        GenerateNpc();
    }

    private void OnGUI()
    {
        // Keep the IMGUI readable on high-DPI displays.
        float scale = Mathf.Max(1f, Screen.width / 640f);
        GUI.matrix = Matrix4x4.Scale(new Vector3(scale, scale, 1f));
        float width = Screen.width / scale;
        float height = Screen.height / scale;

        GUILayout.BeginArea(new Rect(8, 8, width - 16, height - 16));
        GUILayout.Label("Mecojoni demo -- every line below is generated by the grammar VM");

        scroll = GUILayout.BeginScrollView(scroll, GUILayout.ExpandHeight(true));
        foreach (string line in lines)
        {
            GUILayout.Label(line);
        }
        GUILayout.EndScrollView();

        GUILayout.BeginHorizontal();
        if (GUILayout.Button("Generate greeting"))
        {
            GenerateHello();
        }
        if (GUILayout.Button("Generate NPC line"))
        {
            GenerateNpc();
        }
        GUILayout.Label("playerName:");
        playerName = GUILayout.TextField(playerName, GUILayout.MinWidth(120));
        GUILayout.EndHorizontal();
        GUILayout.EndArea();
    }
}
